import Head from "next/head";

// import Hero from "components/Hero";
import ResourcesImLoving from "components/ResourcesImLoving";
import MostRecentPosts from "components/MostRecentPosts";
import FeaturedPosts from "components/FeaturedPosts";

export default function Home() {
  return (
    <div className="max-w-5xl md:mx-auto xl:max-w-7xl">
      <Head>
        <title>Erins Blog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="pt-4 lg:px-4 sm:pt-8 -mx-4 lg:mx-0 flex flex-col">
        <FeaturedPosts />
      </div>

      <div className="px-4 md:flex md:flex-row md:justify-center md:space-x-6 mt-12">
        <div className="max-w-2xl md:max-w-3xl lg:max-w-5xl xl:max-w-7xl space-y-12 md:flex md:space-y-0 md:space-x-12">
          <div className="w-full md:w-1/2">
            <MostRecentPosts />
          </div>

          <div className="w-full md:w-1/2">
            <ResourcesImLoving />
          </div>
        </div>
      </div>

      {/* <Hero /> */}
    </div>
  );
}
