import Head from "next/head";

import Hero from "components/Hero";
import FeaturedPost from "components/FeaturedPost";
import MostRecentPosts from "components/MostRecentPosts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Erins Blog!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <div className="mt-8 px-4 flex justify-center">
        <div className="grid grid-cols-none md:grid-cols-2 gap-x-6">
          <FeaturedPost />

          <MostRecentPosts />
        </div>
      </div>
    </div>
  );
}
